# Generated by Django 2.2 on 2021-11-01 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.TextField()),
                ('lname', models.TextField()),
                ('email', models.TextField()),
                ('birthday', models.DateField(default=datetime.date.today)),
                ('password', models.TextField()),
                ('password_conf', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
